/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlmanacRouteImport } from './routes/almanac'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StoryRouteImport } from './routes/story'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAlmanacRouteImport } from './routes/admin.almanac'
import { Route as AdminBugsRouteImport } from './routes/admin.bugs'
import { Route as AdminGameRouteImport } from './routes/admin.game'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPartnershipsRouteImport } from './routes/admin.partnerships'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalAchievementsRouteImport } from './routes/portal.achievements'
import { Route as PortalAlmanacRouteImport } from './routes/portal.almanac'
import { Route as PortalFriendsRouteImport } from './routes/portal.friends'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalShopRouteImport } from './routes/portal.shop'
import { Route as AdminAdsIdRouteImport } from './routes/admin.ads.$id'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmanacRoute = AlmanacRouteImport.update({
  id: '/almanac',
  path: '/almanac',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlmanacRoute = AdminAlmanacRouteImport.update({
  id: '/almanac',
  path: '/almanac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBugsRoute = AdminBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGameRoute = AdminGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnershipsRoute = AdminPartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAchievementsRoute = PortalAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAlmanacRoute = PortalAlmanacRouteImport.update({
  id: '/almanac',
  path: '/almanac',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFriendsRoute = PortalFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalShopRoute = PortalShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => PortalRoute,
} as any)
const AdminAdsIdRoute = AdminAdsIdRouteImport.update({
  id: '/ads/$id',
  path: '/ads/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/almanac': typeof AlmanacRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/story': typeof StoryRoute
  '/team': typeof TeamRoute
  '/admin/almanac': typeof AdminAlmanacRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/portal/achievements': typeof PortalAchievementsRoute
  '/portal/almanac': typeof PortalAlmanacRoute
  '/portal/friends': typeof PortalFriendsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/shop': typeof PortalShopRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/ads/$id': typeof AdminAdsIdRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/almanac': typeof AlmanacRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/story': typeof StoryRoute
  '/team': typeof TeamRoute
  '/admin/almanac': typeof AdminAlmanacRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/portal/achievements': typeof PortalAchievementsRoute
  '/portal/almanac': typeof PortalAlmanacRoute
  '/portal/friends': typeof PortalFriendsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/shop': typeof PortalShopRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/ads/$id': typeof AdminAdsIdRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/almanac': typeof AlmanacRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/story': typeof StoryRoute
  '/team': typeof TeamRoute
  '/admin/almanac': typeof AdminAlmanacRoute
  '/admin/bugs': typeof AdminBugsRoute
  '/admin/game': typeof AdminGameRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/portal/achievements': typeof PortalAchievementsRoute
  '/portal/almanac': typeof PortalAlmanacRoute
  '/portal/friends': typeof PortalFriendsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/shop': typeof PortalShopRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/ads/$id': typeof AdminAdsIdRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/almanac'
    | '/contact'
    | '/download'
    | '/features'
    | '/login'
    | '/portal'
    | '/signup'
    | '/story'
    | '/team'
    | '/admin/almanac'
    | '/admin/bugs'
    | '/admin/game'
    | '/admin/notifications'
    | '/admin/partnerships'
    | '/admin/players'
    | '/admin/settings'
    | '/admin/transactions'
    | '/portal/achievements'
    | '/portal/almanac'
    | '/portal/friends'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/shop'
    | '/admin/'
    | '/portal/'
    | '/admin/ads/$id'
    | '/api/admin/login'
    | '/api/admin/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/almanac'
    | '/contact'
    | '/download'
    | '/features'
    | '/login'
    | '/signup'
    | '/story'
    | '/team'
    | '/admin/almanac'
    | '/admin/bugs'
    | '/admin/game'
    | '/admin/notifications'
    | '/admin/partnerships'
    | '/admin/players'
    | '/admin/settings'
    | '/admin/transactions'
    | '/portal/achievements'
    | '/portal/almanac'
    | '/portal/friends'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/shop'
    | '/admin'
    | '/portal'
    | '/admin/ads/$id'
    | '/api/admin/login'
    | '/api/admin/logout'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/almanac'
    | '/contact'
    | '/download'
    | '/features'
    | '/login'
    | '/portal'
    | '/signup'
    | '/story'
    | '/team'
    | '/admin/almanac'
    | '/admin/bugs'
    | '/admin/game'
    | '/admin/notifications'
    | '/admin/partnerships'
    | '/admin/players'
    | '/admin/settings'
    | '/admin/transactions'
    | '/portal/achievements'
    | '/portal/almanac'
    | '/portal/friends'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/shop'
    | '/admin/'
    | '/portal/'
    | '/admin/ads/$id'
    | '/api/admin/login'
    | '/api/admin/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlmanacRoute: typeof AlmanacRoute
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  SignupRoute: typeof SignupRoute
  StoryRoute: typeof StoryRoute
  TeamRoute: typeof TeamRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanac': {
      id: '/almanac'
      path: '/almanac'
      fullPath: '/almanac'
      preLoaderRoute: typeof AlmanacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/almanac': {
      id: '/admin/almanac'
      path: '/almanac'
      fullPath: '/admin/almanac'
      preLoaderRoute: typeof AdminAlmanacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bugs': {
      id: '/admin/bugs'
      path: '/bugs'
      fullPath: '/admin/bugs'
      preLoaderRoute: typeof AdminBugsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/game': {
      id: '/admin/game'
      path: '/game'
      fullPath: '/admin/game'
      preLoaderRoute: typeof AdminGameRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partnerships': {
      id: '/admin/partnerships'
      path: '/partnerships'
      fullPath: '/admin/partnerships'
      preLoaderRoute: typeof AdminPartnershipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/achievements': {
      id: '/portal/achievements'
      path: '/achievements'
      fullPath: '/portal/achievements'
      preLoaderRoute: typeof PortalAchievementsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/almanac': {
      id: '/portal/almanac'
      path: '/almanac'
      fullPath: '/portal/almanac'
      preLoaderRoute: typeof PortalAlmanacRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/friends': {
      id: '/portal/friends'
      path: '/friends'
      fullPath: '/portal/friends'
      preLoaderRoute: typeof PortalFriendsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/shop': {
      id: '/portal/shop'
      path: '/shop'
      fullPath: '/portal/shop'
      preLoaderRoute: typeof PortalShopRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/ads/$id': {
      id: '/admin/ads/$id'
      path: '/ads/$id'
      fullPath: '/admin/ads/$id'
      preLoaderRoute: typeof AdminAdsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAlmanacRoute: typeof AdminAlmanacRoute
  AdminBugsRoute: typeof AdminBugsRoute
  AdminGameRoute: typeof AdminGameRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPartnershipsRoute: typeof AdminPartnershipsRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdsIdRoute: typeof AdminAdsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlmanacRoute: AdminAlmanacRoute,
  AdminBugsRoute: AdminBugsRoute,
  AdminGameRoute: AdminGameRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPartnershipsRoute: AdminPartnershipsRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAdsIdRoute: AdminAdsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalAchievementsRoute: typeof PortalAchievementsRoute
  PortalAlmanacRoute: typeof PortalAlmanacRoute
  PortalFriendsRoute: typeof PortalFriendsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalShopRoute: typeof PortalShopRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAchievementsRoute: PortalAchievementsRoute,
  PortalAlmanacRoute: PortalAlmanacRoute,
  PortalFriendsRoute: PortalFriendsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalShopRoute: PortalShopRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlmanacRoute: AlmanacRoute,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  SignupRoute: SignupRoute,
  StoryRoute: StoryRoute,
  TeamRoute: TeamRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
